/*
 * GNU GPL
 */

package calculadora;

/**
 * Interfaz Gráfica de una Calculadora
 * @author Rakinja
 */
public class Calculadora extends javax.swing.JFrame {

    String numero1 ="";
    String numero2 ="";
    int contador_punto = 0;
    int contador_negativo=0;
    int recorrido = 1;
    
    boolean op = false;
    
    /** Creates new form Calculadora */
    public Calculadora() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        resultado = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        etiqueta1 = new javax.swing.JLabel();
        etiqueta_op = new javax.swing.JLabel();
        etiqueta2 = new javax.swing.JLabel();
        op_sum = new javax.swing.JButton();
        op_div = new javax.swing.JButton();
        op_mul = new javax.swing.JButton();
        op_res = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        etiqueta_res = new javax.swing.JLabel();
        op_por = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        num7.setBackground(new java.awt.Color(35, 75, 102));
        num7.setForeground(new java.awt.Color(255, 255, 255));
        num7.setText("7");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });

        num8.setBackground(new java.awt.Color(35, 75, 102));
        num8.setForeground(new java.awt.Color(255, 255, 255));
        num8.setText("8");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });

        num9.setBackground(new java.awt.Color(35, 75, 102));
        num9.setForeground(new java.awt.Color(255, 255, 255));
        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });

        num6.setBackground(new java.awt.Color(35, 75, 102));
        num6.setForeground(new java.awt.Color(255, 255, 255));
        num6.setText("6");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });

        num5.setBackground(new java.awt.Color(35, 75, 102));
        num5.setForeground(new java.awt.Color(255, 255, 255));
        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        num4.setBackground(new java.awt.Color(35, 75, 102));
        num4.setForeground(new java.awt.Color(255, 255, 255));
        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num3.setBackground(new java.awt.Color(35, 75, 102));
        num3.setForeground(new java.awt.Color(255, 255, 255));
        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        num2.setBackground(new java.awt.Color(35, 75, 102));
        num2.setForeground(new java.awt.Color(255, 255, 255));
        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num1.setBackground(new java.awt.Color(35, 75, 102));
        num1.setForeground(new java.awt.Color(255, 255, 255));
        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        punto.setBackground(new java.awt.Color(35, 75, 102));
        punto.setForeground(new java.awt.Color(255, 255, 255));
        punto.setText(".");
        punto.setActionCommand("");
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });

        resultado.setBackground(new java.awt.Color(35, 75, 102));
        resultado.setForeground(new java.awt.Color(255, 255, 255));
        resultado.setText("=");
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        cero.setBackground(new java.awt.Color(35, 75, 102));
        cero.setForeground(new java.awt.Color(255, 255, 255));
        cero.setText("0");
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });

        op_sum.setBackground(new java.awt.Color(35, 75, 102));
        op_sum.setForeground(new java.awt.Color(255, 255, 255));
        op_sum.setText("+");
        op_sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_sumActionPerformed(evt);
            }
        });

        op_div.setBackground(new java.awt.Color(35, 75, 102));
        op_div.setForeground(new java.awt.Color(255, 255, 255));
        op_div.setText("/");
        op_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_divActionPerformed(evt);
            }
        });

        op_mul.setBackground(new java.awt.Color(35, 75, 102));
        op_mul.setForeground(new java.awt.Color(255, 255, 255));
        op_mul.setText("X");
        op_mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_mulActionPerformed(evt);
            }
        });

        op_res.setBackground(new java.awt.Color(35, 75, 102));
        op_res.setForeground(new java.awt.Color(255, 255, 255));
        op_res.setText("-");
        op_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_resActionPerformed(evt);
            }
        });

        limpiar.setBackground(new java.awt.Color(35, 75, 102));
        limpiar.setForeground(new java.awt.Color(255, 255, 255));
        limpiar.setText("CE");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        op_por.setBackground(new java.awt.Color(35, 75, 102));
        op_por.setForeground(new java.awt.Color(255, 255, 255));
        op_por.setText("%");
        op_por.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_porActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(num4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(num7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(num1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(punto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(num2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(num3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(op_sum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(op_res, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(op_por, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(op_mul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(op_div, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(etiqueta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etiqueta_op, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etiqueta2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(etiqueta_res, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(etiqueta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etiqueta_op, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(etiqueta2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiqueta_res, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limpiar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(op_mul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(op_por)
                            .addComponent(op_div)
                            .addComponent(op_sum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(op_res)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num7)
                            .addComponent(num8)
                            .addComponent(num9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num4)
                            .addComponent(num5)
                            .addComponent(num6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num1)
                            .addComponent(num2)
                            .addComponent(num3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(punto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        numero1 += 1;
        if( recorrido == 1 ){
           etiqueta1.setText( numero1 );
        } else
            etiqueta2.setText( numero1 );
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        numero1 += 2;
        if( recorrido == 1 ){
           etiqueta1.setText( numero1 );
        } else
            etiqueta2.setText( numero1 );
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        numero1 += 3;
        if( recorrido == 1 ){
           etiqueta1.setText( numero1 );
        } else
            etiqueta2.setText( numero1 );
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        numero1 += 4;
        if( recorrido == 1 ){
           etiqueta1.setText( numero1 );
        } else
            etiqueta2.setText( numero1 );
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        numero1 += 5;
        if( recorrido == 1 ){
           etiqueta1.setText( numero1 );
        } else
            etiqueta2.setText( numero1 );
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        numero1 += 6;
        if( recorrido == 1 ){
           etiqueta1.setText( numero1 );
        } else
            etiqueta2.setText( numero1 );
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        numero1 += 7;
        if( recorrido == 1 ){
           etiqueta1.setText( numero1 );
        } else
            etiqueta2.setText( numero1 );
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        numero1 += 8;
        if( recorrido == 1 ){
           etiqueta1.setText( numero1 );
        } else
            etiqueta2.setText( numero1 );
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        numero1 += 9;
        if( recorrido == 1 ){
           etiqueta1.setText( numero1 );
        } else
            etiqueta2.setText( numero1 );
        
    }//GEN-LAST:event_num9ActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        System.out.println("el valor es : "+recorrido);
        System.out.println("el punto es : "+contador_punto);
        if( contador_punto == 0 ){
            numero1 += ".";
                if( recorrido == 1 ){
                    etiqueta1.setText( numero1 );
                }else {
                    
                    etiqueta2.setText( numero1 );
                }
            contador_punto=1;
            
        }
    }//GEN-LAST:event_puntoActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
        numero1 += 0;
        if( recorrido == 1 ){
           etiqueta1.setText( numero1 );
        } else
            etiqueta2.setText( numero1 );
    }//GEN-LAST:event_ceroActionPerformed

    private void op_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_divActionPerformed
        if( !op ){
            etiqueta_op.setText( "/" );
            recorrido = 2;
            numero1="";
            contador_negativo = 0;
            contador_punto = 0;
            op = true;
        }
    }//GEN-LAST:event_op_divActionPerformed

    private void op_mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_mulActionPerformed
        if( !op ){
            etiqueta_op.setText( "X" );
            recorrido = 2;
            numero1="";
            contador_negativo = 0;
            contador_punto = 0;
            op = true;
        }
    }//GEN-LAST:event_op_mulActionPerformed

    private void op_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_resActionPerformed
        if( !op && !etiqueta1.getText().equals("") ){
            etiqueta_op.setText( "-" );
            recorrido = 2;
            numero1="";
            contador_negativo = 0;
            op = true;
        }else if( recorrido == 1 && contador_negativo == 0 ){
            if( etiqueta1.getText().equals("") ){
                numero1 += "-";
                etiqueta1.setText( numero1 );
                contador_negativo = 1;
            }
        } else if ( recorrido == 2 && contador_negativo == 0 ){
            if( etiqueta2.getText().equals("") ){
                numero1 += "-";
                etiqueta2.setText( numero1 );
                contador_negativo = 1;
            }
        }
        contador_punto = 0;
        
    }//GEN-LAST:event_op_resActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_limpiarActionPerformed

    private void op_sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_sumActionPerformed
        if( !op ){
            etiqueta_op.setText("+");
            recorrido = 2;
            contador_punto=0;
            contador_negativo = 0;
            numero1="";
            op = true;
        }
    }//GEN-LAST:event_op_sumActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        operaciones();
        //limpiar();
    }//GEN-LAST:event_resultadoActionPerformed

    private void op_porActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_porActionPerformed
        etiqueta_op.setText("%");
        recorrido = 2;
        contador_punto=0;
        numero1="";
    }//GEN-LAST:event_op_porActionPerformed

    public void limpiar(){
        etiqueta1.setText("");
        etiqueta2.setText("");
        etiqueta_res.setText("");
        etiqueta_op.setText("");
        numero1 = "";
        numero2 = "";
        contador_negativo = 0;
        contador_punto = 0;
        recorrido = 1;
        op = false;   
    }
    
    public void operaciones(){
        if( !etiqueta_op.getText().equals("") ){
            
            double n1,n2;
            
            n1 = Double.valueOf( etiqueta1.getText() );
            n2 = Double.valueOf( etiqueta2.getText() );
            
            if( etiqueta_op.getText().equals("+") ){
                numero2 = String.valueOf( n1 + n2);
                etiqueta_res.setText( numero2 );
            }
            if( etiqueta_op.getText().equals("-") ){
                numero2 = String.valueOf( n1 - n2);
                etiqueta_res.setText( numero2 );
            }
            if( etiqueta_op.getText().equals("X") ){
                numero2 = String.valueOf( n1 * n2);
                etiqueta_res.setText( numero2 );
            }
            if( etiqueta_op.getText().equals("/") ){
                if( n2 == 0 ){
                    etiqueta_res.setText( "Math Error..." );
                }else {
                numero2 = String.valueOf( n1/n2 );
                etiqueta_res.setText( numero2 );
                }
            }            
            if( etiqueta_op.getText().equals("%") ){
                if( n1 > -1 && n1 < 101 ){
                    double aux = (n2/100) * n1;
                    etiqueta_res.setText( String.valueOf( aux ) );
                }
                
            }
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cero;
    private javax.swing.JLabel etiqueta1;
    private javax.swing.JLabel etiqueta2;
    private javax.swing.JLabel etiqueta_op;
    private javax.swing.JLabel etiqueta_res;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton op_div;
    private javax.swing.JButton op_mul;
    private javax.swing.JButton op_por;
    private javax.swing.JButton op_res;
    private javax.swing.JButton op_sum;
    private javax.swing.JButton punto;
    private javax.swing.JButton resultado;
    // End of variables declaration//GEN-END:variables

}
